// Package events defines MIRROR's event model.
//
// The single most important idea in this package is the split between
// COMMANDS and EFFECTS.
//
//	COMMAND  an input that the simulation could not have derived by itself:
//	         the operator injects an accident, a fork changes a policy, the
//	         population is seeded. Commands are the authoritative log. Replay
//	         means: start from the initial state implied by (mapParams, seed),
//	         apply commands at their recorded ticks, and step the engine.
//
//	EFFECT   an observation about something the simulation just did:
//	         a vehicle entered a road, a hospital hit capacity, a substation
//	         tripped. Effects are DERIVED. They are never replayed; they are
//	         regenerated identically by the same deterministic computation.
//
// Why this matters. Event-sourcing everything is the obvious move and it is
// wrong here. At 100k vehicles the engine produces on the order of 400k
// VehicleEnteredRoad effects per simulated minute. Persisting those as the
// system of record would mean writing ~2 GB/hour of data whose only purpose is
// to reconstruct something that a 30 MB checkpoint plus a few hundred commands
// reconstructs exactly. So:
//
//	system of record  = initial params + command log (tiny, append-only)
//	fast recovery     = checkpoint + commands since the checkpoint
//	observability     = effect stream, retained on a short ring buffer,
//	                    sampled into Postgres/Loki, never load-bearing
//
// See docs/architecture/event-model.md and docs/adr/ADR-006-event-sourcing.md.
package events

import (
	"fmt"

	"github.com/mirror-sim/mirror/internal/units"
)

type Kind uint16

// Commands. Persisted. Replayed. Never generated by the engine itself.
const (
	CmdNone Kind = iota
	CmdSeedPopulation
	CmdSetPolicy
	CmdInjectAccident
	CmdCloseRoad
	CmdReopenRoad
	CmdPowerFailure
	CmdPowerRestore
	CmdSetWeather
	CmdHospitalSurge
	CmdTransitFailure
	CmdFloodDistrict
	CmdEarthquake
	CmdCommsOutage
	CmdSpawnTraffic
	CmdChaosKillWorker
	CmdChaosDelayEvents
	CmdChaosDropEvents
	CmdChaosCorruptCheckpoint
	cmdMax
)

// EffectBase separates the two ranges. Anything >= EffectBase is derived and is
// dropped on replay.
const EffectBase Kind = 1000

const (
	EvtVehicleEnteredRoad Kind = EffectBase + iota
	EvtVehicleRerouted
	EvtVehicleArrived
	EvtVehicleStranded
	EvtTripStarted
	EvtSignalChanged
	EvtSignalPowerLost
	EvtSignalPreempted
	EvtAccidentOccurred
	EvtRoadClosed
	EvtRoadReopened
	EvtCongestionCritical
	EvtEmergencyDispatched
	EvtEmergencyOnScene
	EvtIncidentResolved
	EvtHospitalAdmission
	EvtHospitalOverloaded
	EvtHospitalDiverted
	EvtHospitalOnBackup
	EvtSubstationTripped
	EvtSubstationRestored
	EvtPowerFailure
	EvtBlackoutDistrict
	EvtTowerOverloaded
	EvtTowerDown
	EvtTransitDeparted
	EvtTransitDenied
	EvtTransitDelayed
	EvtWeatherChanged
	EvtRegionHandoff
	EvtCheckpointWritten
	EvtWorkerLost
	EvtWorkerRecovered
	EvtDivergenceDetected
	evtMax
)

var kindName = map[Kind]string{
	CmdSeedPopulation:         "cmd.seed_population",
	CmdSetPolicy:              "cmd.set_policy",
	CmdInjectAccident:         "cmd.inject_accident",
	CmdCloseRoad:              "cmd.close_road",
	CmdReopenRoad:             "cmd.reopen_road",
	CmdPowerFailure:           "cmd.power_failure",
	CmdPowerRestore:           "cmd.power_restore",
	CmdSetWeather:             "cmd.set_weather",
	CmdHospitalSurge:          "cmd.hospital_surge",
	CmdTransitFailure:         "cmd.transit_failure",
	CmdFloodDistrict:          "cmd.flood_district",
	CmdEarthquake:             "cmd.earthquake",
	CmdCommsOutage:            "cmd.comms_outage",
	CmdSpawnTraffic:           "cmd.spawn_traffic",
	CmdChaosKillWorker:        "cmd.chaos.kill_worker",
	CmdChaosDelayEvents:       "cmd.chaos.delay_events",
	CmdChaosDropEvents:        "cmd.chaos.drop_events",
	CmdChaosCorruptCheckpoint: "cmd.chaos.corrupt_checkpoint",

	EvtVehicleEnteredRoad:  "vehicle.entered_road",
	EvtVehicleRerouted:     "vehicle.rerouted",
	EvtVehicleArrived:      "vehicle.arrived",
	EvtVehicleStranded:     "vehicle.stranded",
	EvtTripStarted:         "trip.started",
	EvtSignalChanged:       "signal.changed",
	EvtSignalPowerLost:     "signal.power_lost",
	EvtSignalPreempted:     "signal.preempted",
	EvtAccidentOccurred:    "incident.accident",
	EvtRoadClosed:          "road.closed",
	EvtRoadReopened:        "road.reopened",
	EvtCongestionCritical:  "traffic.congestion_critical",
	EvtEmergencyDispatched: "emergency.dispatched",
	EvtEmergencyOnScene:    "emergency.on_scene",
	EvtIncidentResolved:    "incident.resolved",
	EvtHospitalAdmission:   "hospital.admission",
	EvtHospitalOverloaded:  "hospital.overloaded",
	EvtHospitalDiverted:    "hospital.diverted",
	EvtHospitalOnBackup:    "hospital.on_backup",
	EvtSubstationTripped:   "power.substation_tripped",
	EvtSubstationRestored:  "power.substation_restored",
	EvtPowerFailure:        "power.failure",
	EvtBlackoutDistrict:    "power.blackout_district",
	EvtTowerOverloaded:     "comms.tower_overloaded",
	EvtTowerDown:           "comms.tower_down",
	EvtTransitDeparted:     "transit.departed",
	EvtTransitDenied:       "transit.denied",
	EvtTransitDelayed:      "transit.delayed",
	EvtWeatherChanged:      "weather.changed",
	EvtRegionHandoff:       "region.handoff",
	EvtCheckpointWritten:   "checkpoint.written",
	EvtWorkerLost:          "worker.lost",
	EvtWorkerRecovered:     "worker.recovered",
	EvtDivergenceDetected:  "determinism.divergence",
}

func (k Kind) String() string {
	if n, ok := kindName[k]; ok {
		return n
	}
	return fmt.Sprintf("kind(%d)", uint16(k))
}

func (k Kind) IsCommand() bool { return k > CmdNone && k < cmdMax }
func (k Kind) IsEffect() bool  { return k >= EffectBase && k < evtMax }

// Severity drives UI treatment and alert routing.
type Severity uint8

const (
	SevInfo Severity = iota
	SevNotice
	SevWarning
	SevCritical
)

var severityName = [...]string{"info", "notice", "warning", "critical"}

func (s Severity) String() string { return severityName[s] }

// Event is a fixed-size record.
//
// Four int64 payload slots instead of a map or an interface: an effect stream
// at 400k events/minute cannot afford an allocation per event, and a fixed
// layout means the whole ring buffer is one contiguous array that the
// WebSocket encoder can walk without touching the heap. The meaning of A..D is
// per-Kind and documented in payload.go.
type Event struct {
	Seq        uint64
	Tick       units.Tick
	Kind       Kind
	Severity   Severity
	Region     int16
	A, B, C, D int64
}

// Log is an append-only sequence of commands. This is the system of record.
//
// It is deliberately a plain slice with a monotonic sequence number rather than
// anything cleverer: the write rate is a few hundred entries per simulated
// hour, and the reader (replay) always wants the whole thing in order. Kafka,
// or even a b-tree, would be pure ceremony at this volume.
type Log struct {
	Cmds []Event
	next uint64
}

// Append inserts a command, keeping the log ordered by (Tick, Seq).
//
// Insertion rather than a plain append, because commands can be SCHEDULED for
// a future tick: an operator sets up a storm at 08:30 and then injects an
// accident for right now. A plain append leaves the log unsorted, and At()
// -- which assumes order -- silently stops finding commands. That failure is
// invisible (no error, the command just never happens) which makes it exactly
// the kind of bug worth designing out rather than documenting around.
//
// Seq is assigned before insertion, so it remains a global submission order and
// two commands scheduled for the same tick execute in the order they were
// submitted.
func (l *Log) Append(e Event) Event {
	if !e.Kind.IsCommand() {
		panic("events: only commands belong in the authoritative log")
	}
	e.Seq = l.next
	l.next++
	i := len(l.Cmds)
	for i > 0 && l.Cmds[i-1].Tick > e.Tick {
		i--
	}
	l.Cmds = append(l.Cmds, Event{})
	copy(l.Cmds[i+1:], l.Cmds[i:])
	l.Cmds[i] = e
	return e
}

// Ordered reports whether the log satisfies the (Tick, Seq) invariant that
// At() and Since() depend on. Exercised by TestLogOrdering.
func (l *Log) Ordered() bool {
	for i := 1; i < len(l.Cmds); i++ {
		if l.Cmds[i-1].Tick > l.Cmds[i].Tick {
			return false
		}
	}
	return true
}

func (l *Log) Len() int     { return len(l.Cmds) }
func (l *Log) Next() uint64 { return l.next }

// Since returns commands with Tick >= from, which is what a checkpoint-based
// recovery needs.
func (l *Log) Since(from units.Tick) []Event {
	i := 0
	for i < len(l.Cmds) && l.Cmds[i].Tick < from {
		i++
	}
	return l.Cmds[i:]
}

// At returns the commands scheduled exactly at a tick. Commands are appended in
// (tick, seq) order by construction, so this is a contiguous window.
func (l *Log) At(t units.Tick) []Event {
	lo := 0
	for lo < len(l.Cmds) && l.Cmds[lo].Tick < t {
		lo++
	}
	hi := lo
	for hi < len(l.Cmds) && l.Cmds[hi].Tick == t {
		hi++
	}
	return l.Cmds[lo:hi]
}

// Clone copies the entire log, including commands scheduled in the future.
//
// This is the right default for a counterfactual fork. "Simulation B is A with
// adaptive signals" means the two runs share not only their history but their
// entire scripted future -- the same accident at the same tick, the same storm
// at the same tick. If a fork silently dropped pending commands, a comparison
// between A and B would be measuring the difference in their event streams as
// much as the difference in their policies, which is exactly the confound a
// counterfactual is supposed to eliminate.
//
// Dropping a scheduled command is a separate, explicit act: see Fork.
func (l *Log) Clone() *Log {
	n := &Log{Cmds: make([]Event, len(l.Cmds)), next: l.next}
	copy(n.Cmds, l.Cmds)
	return n
}

// Fork copies commands up to and including branchTick, deliberately discarding
// anything scheduled after it. Use this when a scenario should keep the
// parent's history but write its own future.
func (l *Log) Fork(branchTick units.Tick) *Log {
	n := &Log{}
	for _, c := range l.Cmds {
		if c.Tick <= branchTick {
			n.Cmds = append(n.Cmds, c)
		}
	}
	n.next = l.next
	return n
}

// Ring is a bounded buffer of effect events for live streaming and for the
// "what just happened" panel.
//
// Bounded on purpose. Effects are not the system of record, so dropping the
// oldest ones under pressure is correct behaviour, not data loss -- and it
// means a slow WebSocket client can never apply backpressure to the simulation
// loop. That property is worth more than complete effect history.
type Ring struct {
	buf     []Event
	head    uint64 // total pushed
	dropped uint64
}

func NewRing(capacity int) *Ring {
	if capacity < 16 {
		capacity = 16
	}
	// Round up to a power of two so index math is a mask.
	c := 16
	for c < capacity {
		c <<= 1
	}
	return &Ring{buf: make([]Event, c)}
}

func (r *Ring) Push(e Event) {
	e.Seq = r.head
	r.buf[r.head&uint64(len(r.buf)-1)] = e
	r.head++
	if r.head > uint64(len(r.buf)) {
		r.dropped = r.head - uint64(len(r.buf))
	}
}

func (r *Ring) Head() uint64    { return r.head }
func (r *Ring) Dropped() uint64 { return r.dropped }
func (r *Ring) Cap() int        { return len(r.buf) }

// ReadFrom copies events with sequence >= from into out, oldest first, and
// returns the sequence the caller should ask for next. If the caller has fallen
// too far behind, it is fast-forwarded and told how many it missed.
func (r *Ring) ReadFrom(from uint64, out []Event, limit int) ([]Event, uint64, uint64) {
	out = out[:0]
	oldest := uint64(0)
	if r.head > uint64(len(r.buf)) {
		oldest = r.head - uint64(len(r.buf))
	}
	var missed uint64
	if from < oldest {
		missed = oldest - from
		from = oldest
	}
	n := 0
	for s := from; s < r.head && n < limit; s++ {
		out = append(out, r.buf[s&uint64(len(r.buf)-1)])
		n++
		from = s + 1
	}
	return out, from, missed
}
